server {
    listen       80;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html;

    # Serve files, try adding .html if not found, else fallback to index.html
    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
